version: "3.8"

services:
  db:
    image: postgres:13.1
    container_name: sample_db
    hostname: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    container_name: sample_django
    hostname: django
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - .:/app
    tty: true
